# Generated by Django 3.0.3 on 2020-05-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='anspap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('nosub', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('opb1', models.BooleanField(default=False)),
                ('opb2', models.BooleanField(default=False)),
                ('opb3', models.BooleanField(default=False)),
                ('opb4', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='qsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('nosub', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=1000)),
                ('option2', models.CharField(max_length=1000)),
                ('option3', models.CharField(max_length=1000)),
                ('option4', models.CharField(max_length=1000)),
                ('opb1', models.BooleanField(default=False)),
                ('opb2', models.BooleanField(default=False)),
                ('opb3', models.BooleanField(default=False)),
                ('opb4', models.BooleanField(default=False)),
            ],
        ),
    ]
