# Generated by Django 3.0.3 on 2020-05-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=1000)),
                ('pwd', models.CharField(max_length=1000)),
                ('quest', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=1000)),
                ('option2', models.CharField(max_length=1000)),
                ('option3', models.CharField(max_length=1000)),
                ('option4', models.CharField(max_length=1000)),
                ('opb1', models.BooleanField(default=False)),
                ('opb2', models.BooleanField(default=False)),
                ('opb3', models.BooleanField(default=False)),
                ('opb4', models.BooleanField(default=False)),
            ],
        ),
    ]
